Create superlinter.yml
camelotls/actions-jira-integration pull request #84
Opened 2021-03-02 14:11 UTC by gioko

2021-03-05 09:04 UTC, sgkiokas requested changes
Thanks a lot for your PR @gioko! I made some comments in order to make it better. Also, please update the PR title in order to conform to the standard `feat: Create superlinter.yml`. The body of the PR should contain a short description of your addition and also a link to the original issue for traceability. Please see [that](https://github.com/camelotls/actions-jira-integration/commit/04fa139d979f1ba0891725c5c34d5233fa0937ce) commit for an example.

Also, the following files can be removed since they will be redundant:

- [linter.yml](https://github.com/camelotls/actions-jira-integration/blob/main/.github/workflows/linter.yml)
- [.eslintrc.json](https://github.com/camelotls/actions-jira-integration/blob/main/.eslintrc.json)

2021-03-05 09:04 UTC, sgkiokas commented on .github/workflows/superlinter.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
I think this is not needed since we are pulling from a public repo.

2021-03-05 09:04 UTC, sgkiokas commented on .github/workflows/superlinter.yml
> +
Please remove this extra line.

2021-03-08 14:18 UTC, closed without merging

2021-03-08 14:23 UTC, gioko commented
Issue #55 is resolved on PR #91